dist: trusty
sudo: required
group: edge
node_js: "8"
jdk: oraclejdk8

services:
- docker

install:
- sudo apt update
- sudo apt install -y build-essential python-dev libzmq3-dev

script:
- npm install --unsafe-perm
- npm test
- npm run codecov
- bash test/travis-bin/sonar.sh

notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/8e145155fbaaf37cffea
    on_success: change
    on_failure: always
    on_start: never
  email: false

addons:
  sonarqube: true
