loadbalancer:
  image: kuzzleio/lb-dev:alpine
  volumes:
    - "../../kuzzle-proxy:/var/app"
  ports:
    - "7511:7511"
    - "7512:7512"
    - "8083:8080"

kuzzle:
  image: kuzzleio/dev:alpine
  command: /scripts/debug.sh
  volumes:
    - "..:/var/app"
    - "/tmp/kbis_node_modules:/var/app/node_modules"
    - "../docker-compose/scripts:/scripts"
    - "../docker-compose/config:/config"
    - "../docker-compose/config/.kuzzlerc:/var/app/.kuzzlerc"
    - "../../kuzzle-plugin-cluster:/var/kuzzle-plugin-cluster"
  ports:
    - "8080:8080"
    - "8081:8081"
  links:
    - rabbit
    - elasticsearch
    - redis
    - loadbalancer:loadbalancer
  environment:
    - MQ_BROKER_ENABLED=1
    - FEATURE_COVERAGE

kuzzle_bis:
  image: kuzzleio/dev:alpine
  command: /scripts/debug.sh
  volumes:
    - "..:/var/app"
    - "/tmp/kbis_node_modules:/var/app/node_modules"
    - "../docker-compose/scripts:/scripts"
    - "../docker-compose/config:/config"
    - "../docker-compose/config/.kuzzlerc:/var/app/.kuzzlerc"
    - "../../kuzzle-plugin-cluster:/var/kuzzle-plugin-cluster"
  links:
    - rabbit
    - elasticsearch
    - redis
    - loadbalancer:loadbalancer
    - kuzzle:master
  environment:
    - MQ_BROKER_ENABLED=1
    - FEATURE_COVERAGE
    - kuzzle_cluster__mode=slave
    - kuzzle_cluster__host=master
    - kuzzle_cluster__port=7911

kuzzle_ter:
  image: kuzzleio/dev:alpine
  command: /scripts/debug.sh
  volumes:
    - "..:/var/app"
    - "/tmp/kter_node_modules:/var/app/node_modules"
    - "../docker-compose/scripts:/scripts"
    - "../docker-compose/config:/config"
    - "../docker-compose/config/.kuzzlerc:/var/app/.kuzzlerc"
    - "../../kuzzle-plugin-cluster:/var/kuzzle-plugin-cluster"
  links:
    - rabbit
    - elasticsearch
    - redis
    - loadbalancer:loadbalancer
    - kuzzle:master
  environment:
    - MQ_BROKER_ENABLED=1
    - FEATURE_COVERAGE
    - kuzzle_cluster__mode=slave
    - kuzzle_cluster__host=master
    - kuzzle_cluster__port=7911

rabbit:
  image: kuzzleio/rabbitmq:alpine
  ports:
    - "61613:61613"
    - "1883:1883"
    - "5672:5672"
    - "15672:15672"

redis:
  image: redis:3.0-alpine

elasticsearch:
  image: kuzzleio/elasticsearch:2.2

rabbit:
  image: kuzzleio/rabbitmq:alpine
  ports:
    - "61613:61613"
    - "1883:1883"
    - "5672:5672"
    - "15672:15672"

redis:
  image: redis:3.0-alpine

elasticsearch:
  image: kuzzleio/elasticsearch:2.2
