version: "2"

services:
  loadbalancer:
    image: kuzzleio/proxy-dev
    container_name: kuzzle_lb
    networks:
      kuzzle-cluster:
        aliases:
          - api
    volumes:
      - "../../kuzzle-load-balancer:/var/app"
    ports:
      - "7511:7511"
      - "7512:7512"
      - "7513:7513"
    environment:
      - lb_backendMode=round-robin

  kuzzle1:
    image: kuzzleio/dev:alpine
    container_name: kuzzle1
    command: bash /scripts/debug.sh
    networks:
      - kuzzle-cluster
    volumes:
      - "../../kuzzle:/var/app"
      - "../../kuzzle-load-balancer:/var/kuzzle-load-balancer"
      - "./tmp/kuzzle1/node_modules:/var/app/node_modules"
      - "./scripts:/scripts"
      - "./config:/config"
      - "..:/var/kuzzle-plugin-cluster"
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - FEATURE_COVERAGE
      - kuzzle_cluster__retryInterval=2000
      - kuzzle_pluginsManager__defaultPlugins__kuzzle-plugin-cluster__path=/var/kuzzle-plugin-cluster
      - kuzzle_pluginsManager__defaultPlugins__kuzzle-plugin-cluster__activated=true
      - kuzzle_pluginsManager__defaultPlugins__kuzzle-plugin-cluster__privileged=true

  kuzzle2:
    image: kuzzleio/dev:alpine
    container_name: kuzzle2
    command: bash /scripts/debug.sh
    networks:
      - kuzzle-cluster
    volumes:
      - "../../kuzzle:/var/app"
      - "../../kuzzle-load-balancer:/var/kuzzle-load-balancer"
      - "./tmp/kuzzle2/node_modules:/var/app/node_modules"
      - "./scripts:/scripts"
      - "./config:/config"
      - "..:/var/kuzzle-plugin-cluster"
    environment:
      - FEATURE_COVERAGE
      - kuzzle_cluster__retryInterval=2000
      - kuzzle_pluginsManager__defaultPlugins__kuzzle-plugin-cluster__path=/var/kuzzle-plugin-cluster
      - kuzzle_pluginsManager__defaultPlugins__kuzzle-plugin-cluster__activated=true
      - kuzzle_pluginsManager__defaultPlugins__kuzzle-plugin-cluster__privileged=true

  kuzzle3:
    image: kuzzleio/dev:alpine
    container_name: kuzzle3
    command: bash /scripts/debug.sh
    networks:
      - kuzzle-cluster
    volumes:
      - "../../kuzzle:/var/app"
      - "../../kuzzle-load-balancer:/var/kuzzle-load-balancer"
      - "./tmp/kuzzle3/node_modules:/var/app/node_modules"
      - "./scripts:/scripts"
      - "./config:/config"
      - "..:/var/kuzzle-plugin-cluster"
    environment:
      - FEATURE_COVERAGE
      - kuzzle_cluster__retryInterval=2000
      - kuzzle_pluginsManager__defaultPlugins__kuzzle-plugin-cluster__path=/var/kuzzle-plugin-cluster
      - kuzzle_pluginsManager__defaultPlugins__kuzzle-plugin-cluster__activated=true
      - kuzzle_pluginsManager__defaultPlugins__kuzzle-plugin-cluster__privileged=true

  redis:
    image: redis:3.0-alpine
    networks: [kuzzle-cluster]

  elasticsearch:
    image: kuzzleio/elasticsearch
    networks: [kuzzle-cluster]

networks:
  kuzzle-cluster:
    driver: bridge
