version: "2"

services:
  loadbalancer:
    image: kuzzleio/dev
    container_name: kuzzle_lb
    command: sh -c 'chmod 755 /var/app/docker-compose/scripts/run-dev.sh && /var/app/docker-compose/scripts/run-dev.sh'
    networks:
      kuzzle-cluster:
        aliases:
          - api
    volumes:
      - "../../kuzzle-load-balancer/docker-compose/config/pm2-dev.json:/config/pm2.json"
    ports:
      - "7511-7513:7511-7513"
    environment:
      - lb_backendMode=round-robin

  kuzzle1:
    image: kuzzleio/dev
    container_name: kuzzle1
    command: sh -c 'chmod 755 /scripts/run-dev.sh && /scripts/run-dev.sh'
    networks:
      - kuzzle-cluster
    volumes:
      - "../../kuzzle:/var/app"
      - "../../kuzzle-load-balancer:/var/kuzzle-load-balancer"
      - "./tmp/kuzzle1/node_modules:/var/app/node_modules"
      - "./scripts:/scripts"
      - "./config/pm2-dev.json:/config/pm2.json"
      - "..:/var/kuzzle-plugin-cluster"
      - "./tmp/kuzzle1/plugin-cluster/node_modules:/var/kuzzle-plugin-cluster/node_modules"
    ports:
      - "8080:8080"
    environment:
      - kuzzle_cluster__retryInterval=2000
      - kuzzle_services__db__host=elasticsearch
      - kuzzle_services__internalCache__node__host=redis
      - kuzzle_services__memoryStorage__node__host=redis
      - kuzzle_services__proxyBroker__host=kuzzle_lb
      - kuzzle_plugins__kuzzle-plugin-cluster__path=/var/kuzzle-plugin-cluster
      - kuzzle_plugins__kuzzle-plugin-cluster__activated=true
      - kuzzle_plugins__kuzzle-plugin-cluster__privileged=true

  kuzzle2:
    image: kuzzleio/dev
    container_name: kuzzle2
    command: sh -c 'chmod 755 /scripts/run-dev.sh && /scripts/run-dev.sh'
    networks:
      - kuzzle-cluster
    volumes:
      - "../../kuzzle:/var/app"
      - "../../kuzzle-load-balancer:/var/kuzzle-load-balancer"
      - "./tmp/kuzzle1/node_modules:/var/app/node_modules"
      - "./scripts:/scripts"
      - "./config/pm2-dev.json:/config/pm2.json"
      - "..:/var/kuzzle-plugin-cluster"
      - "./tmp/kuzzle1/plugin-cluster/node_modules:/var/kuzzle-plugin-cluster/node_modules"
    environment:
      - kuzzle_cluster__retryInterval=2000
      - kuzzle_services__db__host=elasticsearch
      - kuzzle_services__internalCache__node__host=redis
      - kuzzle_services__memoryStorage__node__host=redis
      - kuzzle_services__proxyBroker__host=kuzzle_lb
      - kuzzle_plugins__kuzzle-plugin-cluster__path=/var/kuzzle-plugin-cluster
      - kuzzle_plugins__kuzzle-plugin-cluster__activated=true
      - kuzzle_plugins__kuzzle-plugin-cluster__privileged=true

  kuzzle3:
    image: kuzzleio/dev
    container_name: kuzzle3
    command: sh -c 'chmod 755 /scripts/run-dev.sh && /scripts/run-dev.sh'
    networks:
      - kuzzle-cluster
    volumes:
      - "../../kuzzle:/var/app"
      - "../../kuzzle-load-balancer:/var/kuzzle-load-balancer"
      - "./tmp/kuzzle1/node_modules:/var/app/node_modules"
      - "./scripts:/scripts"
      - "./config/pm2-dev.json:/config/pm2.json"
      - "..:/var/kuzzle-plugin-cluster"
      - "./tmp/kuzzle1/plugin-cluster/node_modules:/var/kuzzle-plugin-cluster/node_modules"
    environment:
      - kuzzle_cluster__retryInterval=2000
      - kuzzle_services__db__host=elasticsearch
      - kuzzle_services__internalCache__node__host=redis
      - kuzzle_services__memoryStorage__node__host=redis
      - kuzzle_services__proxyBroker__host=kuzzle_lb
      - kuzzle_plugins__kuzzle-plugin-cluster__path=/var/kuzzle-plugin-cluster
      - kuzzle_plugins__kuzzle-plugin-cluster__activated=true
      - kuzzle_plugins__kuzzle-plugin-cluster__privileged=true

  redis:
    image: redis:3.0-alpine
    networks: [kuzzle-cluster]

  elasticsearch:
    image: kuzzleio/elasticsearch:2.3.4
    networks: [kuzzle-cluster]

networks:
  kuzzle-cluster:
    driver: bridge
