version: '2'

services:
  loadbalancer:
    extends:
      file: docker-compose.yml
      service: loadbalancer

  kuzzle_one:
    extends:
      file: docker-compose.yml
      service: kuzzle1

  redis:
    extends:
      file: docker-compose.yml
      service: redis

  elasticsearch:
    extends:
      file: docker-compose.yml
      service: elasticsearch

networks:
  kuzzle-cluster:
